// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carriers.sql

package store

import (
	"context"
)

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (name, document)
VALUES ($1, $2)
RETURNING id, name, document, created_at
`

type CreateCarrierParams struct {
	Name     string
	Document *string
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, createCarrier, arg.Name, arg.Document)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const createCarrierWithOwner = `-- name: CreateCarrierWithOwner :one
WITH c AS (
    INSERT INTO carriers (name, document)
    VALUES ($4, $5)
    RETURNING id
)
INSERT INTO users (carrier_id, name, email, password_hash, role)
SELECT c.id, $1, $2, $3, 'carrier'
FROM c
RETURNING id, name, email, password_hash, role, created_at, carrier_id
`

type CreateCarrierWithOwnerParams struct {
	Name         string
	Email        string
	PasswordHash string
	CarrierName  string
	Document     *string
}

// CreateCarrierWithOwner signs a carrier up with the person who runs it, in
// one statement, so a taken e-mail leaves no carrier behind.
func (q *Queries) CreateCarrierWithOwner(ctx context.Context, arg CreateCarrierWithOwnerParams) (User, error) {
	row := q.db.QueryRow(ctx, createCarrierWithOwner,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CarrierName,
		arg.Document,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.CarrierID,
	)
	return i, err
}

const getCarrier = `-- name: GetCarrier :one
SELECT id, name, document, created_at FROM carriers WHERE id = $1
`

func (q *Queries) GetCarrier(ctx context.Context, id int64) (Carrier, error) {
	row := q.db.QueryRow(ctx, getCarrier, id)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}
