// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package store

import (
	"context"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (tracking_code, recipient_name, recipient_email, address, driver_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at
`

type CreateDeliveryParams struct {
	TrackingCode   string
	RecipientName  string
	RecipientEmail string
	Address        string
	DriverID       *int64
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.TrackingCode,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.Address,
		arg.DriverID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at FROM deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id int64) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at FROM deliveries
WHERE $1::text IS NULL OR status = $1::text
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListDeliveriesParams struct {
	Status *string
	Offset int32
	Limit  int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.Address,
			&i.Status,
			&i.DriverID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE deliveries SET
    recipient_name  = coalesce($1, recipient_name),
    recipient_email = coalesce($2, recipient_email),
    address         = coalesce($3, address),
    driver_id       = coalesce($4, driver_id),
    updated_at      = now()
WHERE id = $5
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at
`

type UpdateDeliveryParams struct {
	RecipientName  *string
	RecipientEmail *string
	Address        *string
	DriverID       *int64
	ID             int64
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDelivery,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.Address,
		arg.DriverID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
