// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_events.sql

package store

import (
	"context"
)

const createDeliveryEvent = `-- name: CreateDeliveryEvent :one
INSERT INTO delivery_events (delivery_id, status, note, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, delivery_id, status, note, created_by, created_at, published_at
`

type CreateDeliveryEventParams struct {
	DeliveryID int64
	Status     string
	Note       *string
	CreatedBy  *int64
}

func (q *Queries) CreateDeliveryEvent(ctx context.Context, arg CreateDeliveryEventParams) (DeliveryEvent, error) {
	row := q.db.QueryRow(ctx, createDeliveryEvent,
		arg.DeliveryID,
		arg.Status,
		arg.Note,
		arg.CreatedBy,
	)
	var i DeliveryEvent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Status,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listDeliveryEvents = `-- name: ListDeliveryEvents :many
SELECT id, delivery_id, status, note, created_by, created_at, published_at FROM delivery_events
WHERE delivery_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListDeliveryEvents(ctx context.Context, deliveryID int64) ([]DeliveryEvent, error) {
	rows, err := q.db.Query(ctx, listDeliveryEvents, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryEvent
	for rows.Next() {
		var i DeliveryEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Status,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
