// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package store

import (
	"context"
	"time"
)

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, count(*) AS total FROM deliveries
WHERE carrier_id = $1
  AND created_at >= $2::timestamptz
GROUP BY status
`

type CountDeliveriesByStatusParams struct {
	CarrierID int64
	Since     time.Time
}

type CountDeliveriesByStatusRow struct {
	Status string
	Total  int64
}

// CountDeliveriesByStatus feeds the carrier's dashboard. since limits the
// count to deliveries created from that moment on.
func (q *Queries) CountDeliveriesByStatus(ctx context.Context, arg CountDeliveriesByStatusParams) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus, arg.CarrierID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeliveriesByStatusRow
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnassignedDeliveries = `-- name: CountUnassignedDeliveries :one
SELECT count(*) FROM deliveries
WHERE carrier_id = $1 AND driver_id IS NULL AND status = 'pending'
`

func (q *Queries) CountUnassignedDeliveries(ctx context.Context, carrierID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnassignedDeliveries, carrierID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (carrier_id, tracking_code, recipient_name, recipient_email, address, driver_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id
`

type CreateDeliveryParams struct {
	CarrierID      int64
	TrackingCode   string
	RecipientName  string
	RecipientEmail string
	Address        string
	DriverID       *int64
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.CarrierID,
		arg.TrackingCode,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.Address,
		arg.DriverID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id FROM deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id int64) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
	)
	return i, err
}

const getDeliveryByTrackingCode = `-- name: GetDeliveryByTrackingCode :one
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id FROM deliveries WHERE tracking_code = $1
`

func (q *Queries) GetDeliveryByTrackingCode(ctx context.Context, trackingCode string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByTrackingCode, trackingCode)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id FROM deliveries
WHERE carrier_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListDeliveriesParams struct {
	CarrierID int64
	Status    *string
	Offset    int32
	Limit     int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.CarrierID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.Address,
			&i.Status,
			&i.DriverID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.AnonymizedAt,
			&i.CarrierID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverDeliveries = `-- name: ListDriverDeliveries :many
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id FROM deliveries
WHERE driver_id = $1::bigint
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListDriverDeliveriesParams struct {
	DriverID int64
	Status   *string
	Offset   int32
	Limit    int32
}

func (q *Queries) ListDriverDeliveries(ctx context.Context, arg ListDriverDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDriverDeliveries,
		arg.DriverID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.Address,
			&i.Status,
			&i.DriverID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.AnonymizedAt,
			&i.CarrierID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliveryStatus = `-- name: SetDeliveryStatus :one
UPDATE deliveries SET
    status       = $1,
    completed_at = $2,
    updated_at   = now()
WHERE id = $3 AND status = $4
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id
`

type SetDeliveryStatusParams struct {
	Status      string
	CompletedAt *time.Time
	ID          int64
	FromStatus  string
}

// SetDeliveryStatus only changes the row if the status is still the one the
// caller saw, so two concurrent events cannot both apply.
func (q *Queries) SetDeliveryStatus(ctx context.Context, arg SetDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, setDeliveryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.ID,
		arg.FromStatus,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
	)
	return i, err
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE deliveries SET
    recipient_name  = coalesce($1, recipient_name),
    recipient_email = coalesce($2, recipient_email),
    address         = coalesce($3, address),
    driver_id       = coalesce($4, driver_id),
    updated_at      = now()
WHERE id = $5
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id
`

type UpdateDeliveryParams struct {
	RecipientName  *string
	RecipientEmail *string
	Address        *string
	DriverID       *int64
	ID             int64
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDelivery,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.Address,
		arg.DriverID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
	)
	return i, err
}
