// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package store

import (
	"context"
	"time"
)

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, count(*) AS total FROM deliveries
WHERE carrier_id = $1
  AND created_at >= $2::timestamptz
GROUP BY status
`

type CountDeliveriesByStatusParams struct {
	CarrierID int64
	Since     time.Time
}

type CountDeliveriesByStatusRow struct {
	Status string
	Total  int64
}

// CountDeliveriesByStatus feeds the carrier's dashboard. since limits the
// count to deliveries created from that moment on.
func (q *Queries) CountDeliveriesByStatus(ctx context.Context, arg CountDeliveriesByStatusParams) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus, arg.CarrierID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeliveriesByStatusRow
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnassignedDeliveries = `-- name: CountUnassignedDeliveries :one
SELECT count(*) FROM deliveries
WHERE carrier_id = $1 AND driver_id IS NULL AND status = 'pending'
`

func (q *Queries) CountUnassignedDeliveries(ctx context.Context, carrierID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnassignedDeliveries, carrierID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
    carrier_id, tracking_code, recipient_name, recipient_email, recipient_phone,
    address, postal_code, street, number, complement, district, city, state,
    address_reference, latitude, longitude, driver_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude
`

type CreateDeliveryParams struct {
	CarrierID        int64
	TrackingCode     string
	RecipientName    string
	RecipientEmail   string
	RecipientPhone   string
	Address          string
	PostalCode       string
	Street           string
	Number           string
	Complement       string
	District         string
	City             string
	State            string
	AddressReference string
	Latitude         *float64
	Longitude        *float64
	DriverID         *int64
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.CarrierID,
		arg.TrackingCode,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.RecipientPhone,
		arg.Address,
		arg.PostalCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.AddressReference,
		arg.Latitude,
		arg.Longitude,
		arg.DriverID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude FROM deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id int64) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getDeliveryByTrackingCode = `-- name: GetDeliveryByTrackingCode :one
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude FROM deliveries WHERE tracking_code = $1
`

func (q *Queries) GetDeliveryByTrackingCode(ctx context.Context, trackingCode string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByTrackingCode, trackingCode)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude FROM deliveries
WHERE carrier_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL
       OR lower(tracking_code) LIKE '%' || $3::text || '%'
       OR lower(translate(recipient_name,
                'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑáàâãäéèêëíìîïóòôõöúùûüçñ',
                'aaaaaeeeeiiiiooooouuuucnaaaaaeeeeiiiiooooouuuucn'))
          LIKE '%' || $3::text || '%'
       OR lower(recipient_email) LIKE '%' || $3::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListDeliveriesParams struct {
	CarrierID int64
	Status    *string
	Search    *string
	Offset    int32
	Limit     int32
}

// ListDeliveries lists the carrier's deliveries, newest first. search, when
// given, matches part of the tracking code or of the recipient's name or
// e-mail. The service sends it in lower case, without accents and with the
// LIKE wildcards escaped; translate drops the same accents from the name
// (the letters of foldAccents in internal/delivery), so "joao" finds "João".
func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.CarrierID,
		arg.Status,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.Address,
			&i.Status,
			&i.DriverID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.AnonymizedAt,
			&i.CarrierID,
			&i.RecipientPhone,
			&i.PostalCode,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.AddressReference,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverDeliveries = `-- name: ListDriverDeliveries :many
SELECT id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude FROM deliveries
WHERE driver_id = $1::bigint
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListDriverDeliveriesParams struct {
	DriverID int64
	Status   *string
	Offset   int32
	Limit    int32
}

func (q *Queries) ListDriverDeliveries(ctx context.Context, arg ListDriverDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDriverDeliveries,
		arg.DriverID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.Address,
			&i.Status,
			&i.DriverID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.AnonymizedAt,
			&i.CarrierID,
			&i.RecipientPhone,
			&i.PostalCode,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.AddressReference,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliveryStatus = `-- name: SetDeliveryStatus :one
UPDATE deliveries SET
    status       = $1,
    completed_at = $2,
    updated_at   = now()
WHERE id = $3 AND status = $4 AND anonymized_at IS NULL
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude
`

type SetDeliveryStatusParams struct {
	Status      string
	CompletedAt *time.Time
	ID          int64
	FromStatus  string
}

// SetDeliveryStatus only changes the row if the status is still the one the
// caller saw, so two concurrent events cannot both apply, and if the
// recipient's data was not erased in the meantime.
func (q *Queries) SetDeliveryStatus(ctx context.Context, arg SetDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, setDeliveryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.ID,
		arg.FromStatus,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE deliveries SET
    recipient_name    = $1,
    recipient_email   = $2,
    recipient_phone   = $3,
    address           = $4,
    postal_code       = $5,
    street            = $6,
    number            = $7,
    complement        = $8,
    district          = $9,
    city              = $10,
    state             = $11,
    address_reference = $12,
    latitude          = $13,
    longitude         = $14,
    driver_id         = coalesce($15, driver_id),
    updated_at        = now()
WHERE id = $16 AND anonymized_at IS NULL
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude
`

type UpdateDeliveryParams struct {
	RecipientName    string
	RecipientEmail   string
	RecipientPhone   string
	Address          string
	PostalCode       string
	Street           string
	Number           string
	Complement       string
	District         string
	City             string
	State            string
	AddressReference string
	Latitude         *float64
	Longitude        *float64
	DriverID         *int64
	ID               int64
}

// UpdateDelivery writes every recipient and address field: the service
// merges the change into the current delivery first. The driver is only
// changed when sent. An anonymized delivery is left alone, or an edit racing
// the retention job would write the erased data back.
func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDelivery,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.RecipientPhone,
		arg.Address,
		arg.PostalCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.AddressReference,
		arg.Latitude,
		arg.Longitude,
		arg.DriverID,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
