// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package store

import (
	"context"
)

const deleteExpiredIdempotencyKey = `-- name: DeleteExpiredIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE user_id = $1 AND key = $2 AND created_at < now() - interval '24 hours'
`

type DeleteExpiredIdempotencyKeyParams struct {
	UserID int64
	Key    string
}

func (q *Queries) DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKey, arg.UserID, arg.Key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, request_hash, delivery_id, created_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID int64
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.DeliveryID,
		&i.CreatedAt,
	)
	return i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO NOTHING
RETURNING user_id, key, request_hash, delivery_id, created_at
`

type ReserveIdempotencyKeyParams struct {
	UserID      int64
	Key         string
	RequestHash string
}

// ReserveIdempotencyKey returns no row when the key already exists. A
// concurrent request with the same key waits here until the first one
// commits or rolls back.
func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey, arg.UserID, arg.Key, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.DeliveryID,
		&i.CreatedAt,
	)
	return i, err
}

const setIdempotencyKeyDelivery = `-- name: SetIdempotencyKeyDelivery :exec
UPDATE idempotency_keys SET delivery_id = $3 WHERE user_id = $1 AND key = $2
`

type SetIdempotencyKeyDeliveryParams struct {
	UserID     int64
	Key        string
	DeliveryID *int64
}

func (q *Queries) SetIdempotencyKeyDelivery(ctx context.Context, arg SetIdempotencyKeyDeliveryParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyKeyDelivery, arg.UserID, arg.Key, arg.DeliveryID)
	return err
}
