// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Delivery struct {
	ID             int64
	TrackingCode   string
	RecipientName  string
	RecipientEmail string
	Address        string
	Status         string
	DriverID       *int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}
