// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"
	"time"
)

const claimUnpublishedEvents = `-- name: ClaimUnpublishedEvents :many
SELECT e.id, e.status, e.created_at, d.tracking_code, d.recipient_name, d.recipient_email
FROM delivery_events e
JOIN deliveries d ON d.id = e.delivery_id
WHERE e.published_at IS NULL
ORDER BY e.id
LIMIT $1
FOR UPDATE OF e SKIP LOCKED
`

type ClaimUnpublishedEventsRow struct {
	ID             int64
	Status         string
	CreatedAt      time.Time
	TrackingCode   string
	RecipientName  string
	RecipientEmail string
}

// ClaimUnpublishedEvents locks the next events to publish. SKIP LOCKED lets
// several API instances run the relay without sending an event twice.
func (q *Queries) ClaimUnpublishedEvents(ctx context.Context, limit int32) ([]ClaimUnpublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimUnpublishedEventsRow
	for rows.Next() {
		var i ClaimUnpublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.TrackingCode,
			&i.RecipientName,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsPublished = `-- name: MarkEventsPublished :exec
UPDATE delivery_events SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkEventsPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markEventsPublished, ids)
	return err
}

const skipStaleEvents = `-- name: SkipStaleEvents :execrows
UPDATE delivery_events SET published_at = now()
WHERE published_at IS NULL AND created_at < $1
`

// SkipStaleEvents drops notifications nobody wants anymore, such as the ones
// piled up while RabbitMQ was off.
func (q *Queries) SkipStaleEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, skipStaleEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
