// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package store

import (
	"context"
)

const countPushSubscriptions = `-- name: CountPushSubscriptions :one
SELECT count(*) FROM push_subscriptions WHERE delivery_id = $1
`

func (q *Queries) CountPushSubscriptions(ctx context.Context, deliveryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPushSubscriptions, deliveryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE delivery_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	DeliveryID int64
	Endpoint   string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.DeliveryID, arg.Endpoint)
	return err
}

const deletePushSubscriptionByID = `-- name: DeletePushSubscriptionByID :exec
DELETE FROM push_subscriptions WHERE id = $1
`

func (q *Queries) DeletePushSubscriptionByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByID, id)
	return err
}

const deletePushSubscriptionsByCode = `-- name: DeletePushSubscriptionsByCode :exec
DELETE FROM push_subscriptions s
USING deliveries d
WHERE d.id = s.delivery_id AND d.tracking_code = $1
`

func (q *Queries) DeletePushSubscriptionsByCode(ctx context.Context, trackingCode string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionsByCode, trackingCode)
	return err
}

const listPushSubscriptionsByCode = `-- name: ListPushSubscriptionsByCode :many
SELECT s.id, s.delivery_id, s.endpoint, s.p256dh, s.auth, s.created_at FROM push_subscriptions s
JOIN deliveries d ON d.id = s.delivery_id
WHERE d.tracking_code = $1
ORDER BY s.id
`

func (q *Queries) ListPushSubscriptionsByCode(ctx context.Context, trackingCode string) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByCode, trackingCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (delivery_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (delivery_id, endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth = excluded.auth
`

type UpsertPushSubscriptionParams struct {
	DeliveryID int64
	Endpoint   string
	P256dh     string
	Auth       string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.DeliveryID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
