// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"
)

type Querier interface {
	// ClaimUnpublishedEvents locks the next events to publish. SKIP LOCKED lets
	// several API instances run the relay without sending an event twice.
	ClaimUnpublishedEvents(ctx context.Context, limit int32) ([]ClaimUnpublishedEventsRow, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateDeliveryEvent(ctx context.Context, arg CreateDeliveryEventParams) (DeliveryEvent, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error
	GetDelivery(ctx context.Context, id int64) (Delivery, error)
	GetDeliveryByTrackingCode(ctx context.Context, trackingCode string) (Delivery, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetRefreshToken(ctx context.Context, tokenHash []byte) (GetRefreshTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error)
	ListDeliveryEvents(ctx context.Context, deliveryID int64) ([]DeliveryEvent, error)
	ListDriverDeliveries(ctx context.Context, arg ListDriverDeliveriesParams) ([]Delivery, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	MarkEventsPublished(ctx context.Context, ids []int64) error
	// ReserveIdempotencyKey returns no row when the key already exists. A
	// concurrent request with the same key waits here until the first one
	// commits or rolls back.
	ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (IdempotencyKey, error)
	RevokeRefreshFamily(ctx context.Context, familyID string) error
	// SetDeliveryStatus only changes the row if the status is still the one the
	// caller saw, so two concurrent events cannot both apply.
	SetDeliveryStatus(ctx context.Context, arg SetDeliveryStatusParams) (Delivery, error)
	SetIdempotencyKeyDelivery(ctx context.Context, arg SetIdempotencyKeyDeliveryParams) error
	// SkipStaleEvents drops notifications nobody wants anymore, such as the ones
	// piled up while RabbitMQ was off.
	SkipStaleEvents(ctx context.Context, before time.Time) (int64, error)
	UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error)
	// Marks the token used only if nobody did it first, so two refreshes racing
	// with the same token cannot both succeed.
	UseRefreshToken(ctx context.Context, id int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
