// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDelivery(ctx context.Context, id int64) (Delivery, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error)
}

var _ Querier = (*Queries)(nil)
