// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	UserID    int64
	FamilyID  string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT rt.id, rt.user_id, rt.family_id, rt.expires_at, rt.used_at, rt.revoked_at, u.role
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        int64
	UserID    int64
	FamilyID  string
	ExpiresAt time.Time
	UsedAt    *time.Time
	RevokedAt *time.Time
	Role      string
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.Role,
	)
	return i, err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const useRefreshToken = `-- name: UseRefreshToken :execrows
UPDATE refresh_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL
`

// Marks the token used only if nobody did it first, so two refreshes racing
// with the same token cannot both succeed.
func (q *Queries) UseRefreshToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, useRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
