// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"
	"time"
)

const anonymizeDeliveries = `-- name: AnonymizeDeliveries :one
WITH d AS (
    UPDATE deliveries SET
        recipient_name  = 'Destinatário removido',
        recipient_email = '',
        recipient_phone = '',
        address         = '',
        postal_code     = '',
        street          = '',
        number          = '',
        complement      = '',
        district        = '',
        address_reference = '',
        latitude        = NULL,
        longitude       = NULL,
        anonymized_at   = now(),
        updated_at      = now()
    WHERE anonymized_at IS NULL
      AND status IN ('delivered', 'failed')
      AND completed_at < $1::timestamptz
    RETURNING id
), e AS (
    UPDATE delivery_events SET note = NULL
    WHERE delivery_id IN (SELECT id FROM d) AND note IS NOT NULL
)
SELECT count(*) FROM d
`

// AnonymizeDeliveries erases the recipient of deliveries finished before
// the given time, and the drivers' notes, which are free text and may name
// people. Returns how many deliveries were anonymized.
func (q *Queries) AnonymizeDeliveries(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, anonymizeDeliveries, before)
	var count int64
	err := row.Scan(&count)
	return count, err
}
