// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"
	"time"
)

const anonymizeDeliveries = `-- name: AnonymizeDeliveries :one
WITH d AS (
    UPDATE deliveries SET
        recipient_name  = 'Destinatário removido',
        recipient_email = '',
        recipient_phone = '',
        address         = '',
        postal_code     = '',
        street          = '',
        number          = '',
        complement      = '',
        district        = '',
        address_reference = '',
        latitude        = NULL,
        longitude       = NULL,
        anonymized_at   = now(),
        updated_at      = now()
    WHERE anonymized_at IS NULL
      AND status IN ('delivered', 'failed')
      AND completed_at < $1::timestamptz
    RETURNING id
), e AS (
    UPDATE delivery_events SET note = NULL
    WHERE delivery_id IN (SELECT id FROM d) AND note IS NOT NULL
), s AS (
    DELETE FROM push_subscriptions
    WHERE delivery_id IN (SELECT id FROM d)
)
SELECT count(*) FROM d
`

// AnonymizeDeliveries erases the recipient of deliveries finished before
// the given time, the drivers' notes, which are free text and may name
// people, and the browsers still following them (a failed delivery keeps
// them). Returns how many deliveries were anonymized.
func (q *Queries) AnonymizeDeliveries(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, anonymizeDeliveries, before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now()
`

// DeleteExpiredRefreshTokens drops the refresh tokens that no longer log
// anyone in. Reuse is only checked on tokens that have not expired, so
// nothing is lost.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldIdempotencyKeys = `-- name: DeleteOldIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

// DeleteOldIdempotencyKeys drops the keys older than the 24 hours in which a
// retry can still use them.
func (q *Queries) DeleteOldIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
