// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRouteItem = `-- name: AddRouteItem :execrows
INSERT INTO route_items (route_id, delivery_id, position)
SELECT $1, $2,
       coalesce(max(position), 0) + 1
FROM route_items WHERE route_id = $1
ON CONFLICT (route_id, delivery_id) DO NOTHING
`

type AddRouteItemParams struct {
	RouteID    int64
	DeliveryID int64
}

// AddRouteItem puts the delivery at the end of the route; adding it twice
// changes nothing and affects no rows.
func (q *Queries) AddRouteItem(ctx context.Context, arg AddRouteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRouteItem, arg.RouteID, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDelivery = `-- name: ClaimDelivery :one
UPDATE deliveries SET driver_id = $1, updated_at = now()
WHERE id = $2 AND driver_id IS NULL
RETURNING id, tracking_code, recipient_name, recipient_email, address, status, driver_id, created_at, updated_at, completed_at, anonymized_at, carrier_id, recipient_phone, postal_code, street, number, complement, district, city, state, address_reference, latitude, longitude
`

type ClaimDeliveryParams struct {
	DriverID *int64
	ID       int64
}

// ClaimDelivery assigns a delivery with no driver to the driver who scanned
// it; one that already has a driver is left alone.
func (q *Queries) ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, claimDelivery, arg.DriverID, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.TrackingCode,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.Address,
		&i.Status,
		&i.DriverID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.AnonymizedAt,
		&i.CarrierID,
		&i.RecipientPhone,
		&i.PostalCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.AddressReference,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const ensureRoute = `-- name: EnsureRoute :one
INSERT INTO routes (carrier_id, driver_id, route_date)
VALUES ($1, $2, $3)
ON CONFLICT (driver_id, route_date) DO UPDATE SET route_date = excluded.route_date
RETURNING id, carrier_id, driver_id, route_date, created_at
`

type EnsureRouteParams struct {
	CarrierID int64
	DriverID  int64
	RouteDate pgtype.Date
}

// EnsureRoute returns the driver's route for the day, creating it on first use.
func (q *Queries) EnsureRoute(ctx context.Context, arg EnsureRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, ensureRoute, arg.CarrierID, arg.DriverID, arg.RouteDate)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.CarrierID,
		&i.DriverID,
		&i.RouteDate,
		&i.CreatedAt,
	)
	return i, err
}

const listRouteItems = `-- name: ListRouteItems :many
SELECT d.id, d.tracking_code, d.recipient_name, d.recipient_email, d.address, d.status, d.driver_id, d.created_at, d.updated_at, d.completed_at, d.anonymized_at, d.carrier_id, d.recipient_phone, d.postal_code, d.street, d.number, d.complement, d.district, d.city, d.state, d.address_reference, d.latitude, d.longitude, ri.position
FROM route_items ri
JOIN deliveries d ON d.id = ri.delivery_id
WHERE ri.route_id = $1
ORDER BY ri.position, ri.added_at
`

type ListRouteItemsRow struct {
	Delivery Delivery
	Position int32
}

func (q *Queries) ListRouteItems(ctx context.Context, routeID int64) ([]ListRouteItemsRow, error) {
	rows, err := q.db.Query(ctx, listRouteItems, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteItemsRow
	for rows.Next() {
		var i ListRouteItemsRow
		if err := rows.Scan(
			&i.Delivery.ID,
			&i.Delivery.TrackingCode,
			&i.Delivery.RecipientName,
			&i.Delivery.RecipientEmail,
			&i.Delivery.Address,
			&i.Delivery.Status,
			&i.Delivery.DriverID,
			&i.Delivery.CreatedAt,
			&i.Delivery.UpdatedAt,
			&i.Delivery.CompletedAt,
			&i.Delivery.AnonymizedAt,
			&i.Delivery.CarrierID,
			&i.Delivery.RecipientPhone,
			&i.Delivery.PostalCode,
			&i.Delivery.Street,
			&i.Delivery.Number,
			&i.Delivery.Complement,
			&i.Delivery.District,
			&i.Delivery.City,
			&i.Delivery.State,
			&i.Delivery.AddressReference,
			&i.Delivery.Latitude,
			&i.Delivery.Longitude,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRouteItem = `-- name: RemoveRouteItem :execrows
DELETE FROM route_items WHERE route_id = $1 AND delivery_id = $2
`

type RemoveRouteItemParams struct {
	RouteID    int64
	DeliveryID int64
}

func (q *Queries) RemoveRouteItem(ctx context.Context, arg RemoveRouteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRouteItem, arg.RouteID, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRoutePositions = `-- name: SetRoutePositions :exec
UPDATE route_items ri SET position = u.position
FROM unnest($2::bigint[]) WITH ORDINALITY AS u(delivery_id, position)
WHERE ri.route_id = $1 AND ri.delivery_id = u.delivery_id
`

type SetRoutePositionsParams struct {
	RouteID     int64
	DeliveryIds []int64
}

// SetRoutePositions numbers the route's deliveries in the order of the ids
// given, from 1.
func (q *Queries) SetRoutePositions(ctx context.Context, arg SetRoutePositionsParams) error {
	_, err := q.db.Exec(ctx, setRoutePositions, arg.RouteID, arg.DeliveryIds)
	return err
}
